base/autotools_package.py
scripts/setup_cygstack.py

This is for use with hashdist/hashdist#302, although unlike that there should be nothing holding this one back.

initial compatiblity with python 3

---

pkgs/buildbot-slave.yaml
pkgs/buildbot.yaml
pkgs/git.yaml
pkgs/golang.yaml
pkgs/supervisor.yaml

Here's a PR with some updates to the latest stables of various 'helper' packages for what I do.

Update stable to a number of packages

---

pkgs/guilt.yaml

There are a number of fixes from the upstream, this is a v0.36-rc1 but it's good enough.

guilt: update with minor fixes

---

pkgs/git.yaml
pkgs/quilt.yaml

Update git and quilt to latest stables

Update stable -- git and quilt

---

pkgs/bcfg2.yaml
pkgs/lockfile.yaml
pkgs/python-daemon.yaml

Initial add of bcfg2 configuration management from Argonne National Labs

bcfg2: Initial add of bcfg2 configuration management

---

pkgs/trilinos.yaml

Upgrade Trilinos

---

pkgs/ansible.yaml

ansible: update to latest stable

---

pkgs/pycgal.yaml

added  missing swig dependency

---

pkgs/gcc/rpath.patch

Update the patch (move the rpath one line down)

---

pkgs/cmake.yaml

Now even the bootstrap will run in parallel.

Update CMake, compile in parallel

---

pkgs/terraform.yaml

terraform: Initial add of package

---

pkgs/gox.yaml
pkgs/packer.yaml

packer: Initial add of package

---

pkgs/jinja2.yaml
pkgs/pelican.yaml
pkgs/python-markdown.yaml
pkgs/typogrify.yaml

relies on https://github.com/hashdist/hashstack/pull/682

fix pelican

---

pkgs/paraview/paraview.yaml

I built it and tested it, it seems to be working.

Update paraview to 4.3.1

---

pkgs/libssh2.yaml

libssh2: Initial add

---

pkgs/hugo.yaml

hugo: update to latest stable

---

pkgs/libsdl2.yaml
pkgs/libsdl2_ttf.yaml

SDL2 toolkit for building gui's

sdl2: Initial add of libsdl2 and libsdl2-ttf

---

pkgs/genshi.yaml

genshi: Initial add of genshi templating library

---

pkgs/valgrind.yaml

Adding profile for Valgrind (http://valgrind.org/).

Initial commit for Valgrind profile.

---

pkgs/openblas.yaml

openblas: turn off threading by default

---

pkgs/node.yaml

Update to nodejs 0.12.2

---

pkgs/Tempita.yaml
pkgs/buildbot.yaml
pkgs/cryptography.yaml
pkgs/decorator.yaml
pkgs/lockfile.yaml
pkgs/pbr.yaml

Some dependencies weren't complete, this PR fixes this

Fix up dependencies for buildbot and bcfg2

---

examples/proteus.Darwin.yaml
examples/proteus.linux2.yaml
pkgs/pillow.yaml

used for proteus parallel plotting

add pillow

---

pkgs/terraform.yaml

Periodic update to a recent stable version

terraform: update package to recent stable version

---

pkgs/mesa.yaml

update source URL for mesa 10.2.4

---

pkgs/terraform.yaml

terraform: update to latest tip which is stable

---

pkgs/flufl_lock.yaml
pkgs/instant.yaml

Add flufl_lock as runtime dependency for instant

---

pkgs/scotch/Make.inc.linux
pkgs/scotch/scotch.yaml

scotch: add missing dependency on zlib

---

pkgs/slepc.yaml

https://listas.upv.es/pipermail/slepc-announce/2015-February/000021.html

Fix download url of SLEPc

---

pkgs/terraform.yaml

regular update to recent stable version

Update terraform to recent stable version

---

pkgs/cmake.yaml
pkgs/doxygen.yaml

Update CMake and Doxygen.

---

pkgs/suitesparse.yaml

update link to suitesparse 4.0.2 package

---

pkgs/python/2.5.2-ctypes-util-find_library.patch
pkgs/python/2.5.2-tkinter-x11.patch
pkgs/python/2.6.5-FD_SETSIZE.patch
pkgs/python/2.6.5-export-PySignal_SetWakeupFd.patch
pkgs/python/2.6.5-ncurses-abi6.patch
pkgs/python/2.7.3-dbm.patch
pkgs/python/2.7.3-dylib.patch
pkgs/python/2.7.3-getpath-exe-extension.patch
pkgs/python/2.7.3-no-libm.patch
pkgs/python/python.yaml

This is close to working: some extension modules aren't being detected/compiled properly.  I think this may have something to do with how broken Windows is with respect to locating dynamic libraries (ie, no RPATH, just PATH).
Will do some more investigating now that I know about `cygcheck`.

[WIP] Python on Cygwin64.

---

pkgs/fabric.yaml

This brings the fabric package up to date

Update fabric to 1.10.2 stable

---

pkgs/joblib.yaml

joblib: update to recent release

---

pkgs/blosc.yaml

This adds the blosc python package

blosc: Initial add of python blosc compression package

---

pkgs/daetk/daetk.yaml
pkgs/numpy/numpy.yaml
pkgs/petsc/petsc.py
pkgs/superlu/make.inc.sgiicex
pkgs/superlu/superlu.yaml

Cherry picked  support for SGI ICEX from stable/spirit branch. This shouldn't break  anything for anyone else. Note: stable/spirit still has changes due to  SSL issues on that machine that required using alternative URL's for  some of the sources. Once  those issues go away, commits in this PR  should be all that is needed.

Add sgi icex support

---

pkgs/isort.yaml
pkgs/yapf.yaml

These are just nice to have formatters for python code

Add isort  and yapf

---

pkgs/golang.yaml

golang: update to 1.5.1

---

pkgs/pythreejs.yaml

added  pythreejs pkg

---

pkgs/flatdict.yaml
pkgs/toolz.yaml

Add convenience libraries for python

Add flatdict toolz

---

pkgs/watchman.yaml

Watchman exists to watch files and record when they change. It can
also trigger actions (such as rebuilding assets) when matching files
change.
See https://facebook.github.io/watchman/

Add watchman

---

pkgs/node.yaml

Update to nodejs v5

---

pkgs/python/python.yaml

Add Python 3.5

---

pkgs/openssl/openssl.yaml

openssl: prologue before configure

---

pkgs/schematics.yaml

This is a convenient data structures library.

schematics: Initial add of Python Data Structures for Humans

---

pkgs/terraform.yaml

terraform: update to latest stable build

---

pkgs/Click.yaml
pkgs/PyECLib.yaml
pkgs/chest.yaml
pkgs/dask.yaml
pkgs/fadvise.yaml
pkgs/partd.yaml

Initial add of click for building command line apps, fadvise for hinting linux based systems about IO and pyeclib for erasure coding data.

Initial add of some useful libraries

---

pkgs/bloscpack.yaml
pkgs/castra.yaml
pkgs/chest.yaml
pkgs/cloudpickle.yaml
pkgs/dask.yaml
pkgs/heapdict.yaml
pkgs/locket.yaml
pkgs/partd.yaml
pkgs/sortedcontainers.yaml

Fix up a number of dependencies and update dask to latest stable

Fixup dask dependencies for fresh installs and update dask

---

pkgs/ansible.yaml

this updates ansible to the latest 2.0 release

ansible: update to latest 2.0 stable

---

pkgs/flufl_lock.yaml

flufl_lock: copy __init__.py to correct location also on OS X

---

pkgs/host-pytest-cov.yaml
pkgs/host-pytest.yaml
pkgs/host-setuptools.yaml
pkgs/pytest-cov.yaml

This also adds host packages for setuptools, pytest and pytest-cov.

Add package pytest-cov

---

pkgs/scientificpython.yaml

Fix ScientificPython url

---

pkgs/libevent.yaml

Fix libevent url typo

---

pkgs/paraview/paraview.yaml

I tested it and it seems to work.

Update Paraview to 5.0.0

---

pkgs/adios.yaml

https://www.olcf.ornl.gov/center-projects/adios/

Add the Adios library

---

pkgs/abinit.yaml

Upgrade abinit

---

pkgs/antlr4.yaml

It has different tarballs from Python 2 and Python 3.

Add the antlr4 package

---

pkgs/openssl/openssl.yaml
pkgs/ruby.yaml

Update to openssl-1.0.2h and ruby-2.3.1

---

pkgs/node.yaml

Straightforward version update

Update NodeJS to version 6.9.4

---

pkgs/cmake.yaml

Update to cmake 3.8.0
