pkgs/fenicstools.yaml

Missing dependency on fenicstools. It will not break the installation, but when importing it will result in
```python
>>> from fenicstools import *
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usit/abel/u1/aslakwb/nobackup/hashstack/fenics.dolfin.eps/lib/python2.7/site-packages/fenicstools/__init__.py", line 2, in <module>
from StructuredGrid import StructuredGrid, ChannelGrid
File "/usit/abel/u1/aslakwb/nobackup/hashstack/fenics.dolfin.eps/lib/python2.7/site-packages/fenicstools/StructuredGrid.py", line 10, in <module>
import pyvtk, h5py, copy
ImportError: No module named h5py
```

Add h5py as dependency on fenicstools

---

pkgs/mpmath.yaml

This is needed for the git version of sympy and once sympy is released, for the released version as well.

Add mpmath 0.19

---

pkgs/parmetis/parmetis.yaml

This overrides the parmetis/metis library install names to their
absolute paths.  This fixes a number of problems that arise when
downstream packages try to dynamically link them.

Fix install name on parmetis/metis libraries

---

pkgs/automake.yaml
pkgs/coreutils.yaml
pkgs/diffutils.yaml

@jcftang you added the initial packages --- any reason why you added such old versions? They don't build anymore on my laptop. This PR fixes it.
The only downside that I can see is that the newest versions are only distributed as `.xz` archives (lzma), which means that `hit` with default Python can't unpack them. I had to install `python-lzma` into my Ubuntu.
I also fully uninstalled any automake/autotools packages, so that I can check that these build (i.e. I discovered the need for 801503f71f41f02e3600b49d043a4276fcfbe20f using this approach).

Autotools update

---

pkgs/pyliblzma.yaml
pkgs/xz.yaml

This module is needed for `hit` now, as some packages are only distributed as `.xz` archives.

Fix the lzma module

---

pkgs/openssl/openssl.yaml
pkgs/petsc/petsc.py

When building `python` with HashDist it will be built with `openssl` and when building `petsc` it will by default be built with `ssl` from the system. This leads to problems like the following when building `dolfin`:
CMake Warning at bench/fem/speedup/cpp/CMakeLists.txt:44 (add_executable):
Cannot generate a safe runtime search path for target bench_solve-poisson
because files in some directories may conflict with libraries in implicit
directories:
runtime library [libssl.so.1.0.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/martinal/.hashdist/bld/profile/5c5xotjofrcc/lib
runtime library [libcrypto.so.1.0.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
/home/martinal/.hashdist/bld/profile/5c5xotjofrcc/lib
Some of these libraries may not be found correctly.
The …

Build PETSc with ssl only when a dependency

---

pkgs/gcc/gcc.yaml
pkgs/gcc/rpath.patch

The patch adds @@ARTIFACT@@ at the proper place in the source code and we then
replace it for ${ARTIFACT} using sed.

Make gcc embed rpath automatically

---

pkgs/bcfg2.yaml

This version is considered to be stable however it does not function
correctly on older versions of python (namely versions on EL5)

bcfg2: update to 1.3.5 stable version

---

pkgs/gcc/gcc.yaml

Without this patch, gcc build fails with
2015/02/21 08:56:16 - INFO: [package:run_job] sed: 1: "gcc/config/i386/gnu-user.h": extra characters at the end of g command
2015/02/21 08:56:16 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1

gcc: OSX has bsd sed, should depend on gnu sed

---

pkgs/python/python.yaml

We often require Python to be built with `gdbm`, so it would be nice if this could be the default. What do you think?

Add gdbm to default build dependencies for Python

---

pkgs/dolfin/dolfin.py

Remove TAO as additional DOLFIN dependency. Since petsc-3.5 TAO is included in PETSC and should be automatically enabled and not considered any more as an additional dependency. The following configuration disable TAO from dolfin by default without any reason.

Remove TAO as additional DOLFIN dependency

---

pkgs/mshr.yaml

I think that python should be added as a dependence for `mshr`. Without that, hashdist uses my (old!) system python (2.4 in my case). At least this addition solved my problem. I think that this will solve also this issue: http://fenicsproject.org/pipermail/fenics-support/2015-February/001299.html

Add python as mshr dependence

---

pkgs/mesa.yaml

For example on RHEL6, mesa needs the following profile:
```
mesa:
xlibgl_cflags: ' '
xlibgl_libs: '-lXext -lX11'
```
If you build mesa just with the usual profile:
```
mesa:
```
Then the two environment variables XLIBGL_CFLAGS and XLIBGL_LIBS will be empty,
and they should not affect the build (e.g. if mesa was working before, it
should continue working).
Fixes #675.

Allow to set XLIBGL_CFLAGS/LIBS from a profile

---

pkgs/exodus/exodus.yaml
pkgs/exodus/include_path_fix.patch

The Python wrappers work great with Hashdist, after I patched them (also the `NETCDF_SO_ROOT` and `PYTHON_INSTALL` must be set when calling cmake, those variables are then hardwired in the python wrapper, otherwise the `exodus` module fails to import). Here is an example of usage:
```
In [1]: from exodus import exodus
In [2]: e = exodus('furnace.exo', array_type='numpy')
You are using exodus.py v 1.02 (beta), a python wrapper of some of the exodus II library.
Copyright (c) 2013,2014 Sandia Corporation. Under the terms of Contract DE-AC04-94AL85000
with Sandia Corporation, the U.S. Government retains certain rights in this software.
Opening exodus file: furnace.exo
In [3]: e.get_elem_id_map()
Out[3]: array([       1,        2,        3, ..., 15525656, 15525657, 15525658])
```

Add the ExodusII library

---

pkgs/geos.yaml
pkgs/shapely.yaml

We can't use a release since we need
https://github.com/Toblerity/Shapely/pull/241
This also requires:
https://github.com/hashdist/hashdist/commit/d3a39c57

Add Shapely (Development branch)

---

pkgs/openblas.yaml

I found that the numpy package is not able to find openblas at compile time, because it is looking in `$OPENBLAS_DIR/lib` and `OPENBLAS_DIR` is not set in `openblas.yaml `. I think that this setting should be unable. At least with this change numpy finds openblas for me.

set OPENBLAS_DIR in openblas.yaml when build dependencies

---

pkgs/coffeescript.yaml

This is a bit of an experiment in packaging node.js modules. Since there is basically no stable node.js module, the node package manager makes private installs of all dependencies for each package (recursively).
However, the coffeescript transpiler has no dependencies so its actually easy ;-)

Add coffeescript

---

pkgs/glm.yaml
pkgs/trilinos.yaml

See the commit logs. Now one can switch to git version of Trilinos just by changing the sources, and e.g. the latest master builds without changing anything else.

Trilinos update

---

pkgs/netcdf4/max_dims.patch
pkgs/netcdf4/netcdf4.yaml

Previously it failed to apply (due to white space), now it works again.

netcdf: Rebase the patch on top of the latest code

---

pkgs/hypre.yaml

The rpath-fix should be applied to the real library not to the symlink.
If applied to the symlink (i.e. libHYPRE.so), the symlink is changed to a copy of the file and the rpath of the original library (i.e. libHYPRE-x.x.x.so)  file is not fixed.

hypre rpath-fix

---

pkgs/doxygen.yaml

Doxygen has a dependency on Flex. See build log here:
```
2015/04/23 21:57:58 - INFO: [package:run_job]   Autodetected platform linux-g++... 
2015/04/23 21:57:58 - INFO: [package:run_job]   Checking for GNU make tool... using /usr/bin/make
2015/04/23 21:57:58 - INFO: [package:run_job]   Checking for GNU install tool... using /usr/bin/install
2015/04/23 21:57:58 - INFO: [package:run_job]   Checking for dot (part of GraphViz)... using /usr/bin/dot
2015/04/23 21:57:59 - INFO: [package:run_job]   Checking for python... using /home/villanueva/.hashdist/bld/profile/7zzysldrvpy3/bin/python2
2015/04/23 21:57:59 - INFO: [package:run_job]   Checking for perl... using /usr/bin/perl
2015/04/23 21:57:59 - INFO: [package:run_job]   Checking for flex... not found!
2015/04/23 21:57:59 - ERROR: …
```

Update doxygen.yaml to set dependency on Flex

---

pkgs/httpie.yaml

This is a curl alternative and is very useful for testing against web based api's

httpie: initial add of package, this is a curl alternative

---

pkgs/gmp.yaml
pkgs/gmp/gmp.yaml
pkgs/gmp/osx_10_10_fix.patch

GMP OS X 10.10 fix

---

pkgs/backports-ssl_match_hostname.yaml
pkgs/ipython.yaml
pkgs/jinja2.yaml
pkgs/tornado.yaml

- add missing dependency on markupsafe to jinja2
- add missing dependency on jsonschema to ipython
- update tornado to 4.1 (required for IPython 3)
- add backports.ssl_match_hostname (required for tornado 4)

update IPython to 3.1

---

pkgs/openjpeg.yaml

Note: I couldn't get pillow to use this as its jpeg2000 lib

openjpeg 1.5.1 from dev site, used by grib_api

---

pkgs/ode.yaml

This eliminates the need for setting LD_LIBRARY_PATH when running ode from python.

add -R switch to ode python bindings

---

base/cmake_package.py
pkgs/cmake.yaml

See the commit messages for more information.
This is a change in an important package, so let's check that it (at the latest commit 9aed1265a8886a5e514ba78813953fd2c94e16d5):
Fixes #746.
This is ready for review.

Fix CMake on OSX 10.10

---

pkgs/openssl/openssl.yaml

@certik all I did here is copy your approach in the rpath_openssl branch to the newer version of openssl.yaml, which is in openssl/openssl.yaml and applies a patch, etc.

applied rpath fixes for  linux

---

base/setuptools_package.yaml
pkgs/pillow.yaml

added the bits that point to the hashstack versions of  the dependencies and enforces  the related support in PIL.

added options for <#> versions of png(zlib), freetype, and jpeg2K

---

pkgs/git.yaml

This fixes a build failure on OS X 10.10. Unfortunately, this disabled https
access, so it is only enabled if 'disable_crypto' parameter is 'true'.

git: allow to set NO_APPLE_COMMON_CRYPTO=1

---

pkgs/gcc/gcc.yaml

Fixes #742.
I tested this, it is ready for review.

gcc: install fixed dispatch/object.h header file

---

examples/hd_base.Darwin.yaml

@cekees, @ahmadia let me know what you think.
This profile requires #771 to be merged (well, strictly speaking it will build even without it, but then some other packages that you try to build with gcc will fail, so it's better to have it in, then you do not need to recompile once it is merged). I used the latest master (4637543).

Add hd_base example profile for OS X

---

pkgs/boost/boost.yaml

boost: run patchelf on the libraries, not on the symlinks

---

pkgs/armadillo.yaml

Armadillo does not support out-of-source builds.

Add Armadillo package

---

pkgs/suitesparse.yaml

The url for suitesparse was broken. This PR fixes this.

suitesparse: fix broken url

---

pkgs/boost/boost.yaml
pkgs/boost/call_once_variadic.patch

boost: add patch to fix problems with gcc5

---

pkgs/boost/boost.yaml

This PR adds auto detection of the address-model (32/64 bits) for Boost. The old parameter `address_model` will override the auto detection (maybe needed for cross compilation).

boost: auto detect address-model

---

pkgs/scikit-learn.yaml

Now one can execute SciPy tutorials notebooks (https://github.com/amueller/scipy_2015_sklearn_tutorial).

Update scikit-learn to 0.16.1

---

pkgs/flex.yaml

Flex wasn't building on Cygwin.

flex: Remove -no-undefined on Cygwin.

---

pkgs/oauthlib.yaml
pkgs/pcs_api.yaml
pkgs/requests_oauthlib.yaml

dependencies for https://github.com/hashdist/hashdist/pull/314

added  pcs_api and dependencies

---

pkgs/opentidalfarm.yaml

This pull request updates the URL and hashdist key for the OpenTidalFarm package to 1.5.

Update OpenTidalFarm to 1.5

---

pkgs/aioeventlet.yaml
pkgs/eventlet.yaml
pkgs/libevent.yaml
pkgs/trollius.yaml

Trollius is a 'backport' of asyncio to python2 and aioeventlet is a library that uses this.

aioeventlet: Initial add of aioeventlet package and trollius (asyncio)

---

pkgs/python/python.yaml

This is a periodic update.
2.7.10 built cleanly for me and the dependencies that I use.

python: update to 2.7.10

---

examples/proteus.garnet.gnu.yaml
pkgs/numpy/numpy.yaml

updates the base proteus stack and fixes a missing symbol error at runtime for numpy in a backward compatible way.

updating  Cray XE6 configs

---

pkgs/cgal.yaml
pkgs/pycgal.yaml

@johannesring I'm putting this up in case it is of use.  I don't use cgal much, and dolfin is the only other stack I know that  might use  it.  It's basically just an update to a more recent version of cgal and a reflection of the switch from google code to  github for the python bindings hosting.

updated versions and url's to github, enabled core and  image

---

pkgs/daetk/arch.cygwin
pkgs/daetk/arch.darwin
pkgs/daetk/arch.linux
pkgs/daetk/daetk.yaml
pkgs/petsc4py/petsc4py.yaml
pkgs/petsc4py/petsc4py_install_conf_3.6.0.patch
pkgs/proteus.yaml

@johannesring I tested the petsc 3.6.1 version you added, and it is working fine for me. This PR has some of the changes petsc4py and daetk that  I ended up making to run proteus with the new version.

updated petsc4py and  daetk to work with petsc v3.6.1

---

examples/proteus.tamucluster.yaml

which gives a stack profile for users who wish to build on the numerical analysis Mathematics clusters located at texas a&m university.

add proteus.tamucluster.yaml to stack/examples 

---

pkgs/gccxml/fix_redefinition.patch
pkgs/gccxml/gccxml.yaml

gccxml: add patch to fix build problems with gcc 5.1

---

pkgs/ruby.yaml

This fixes a bug in ruby where it couldn't connect to its own server
due to a SSL/TLS incompatibility:
$ hit develop
$ ./default/bin/gem --install-dir ./default install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/latest_specs.4.8.gz)
See also: https://github.com/rubygems/rubygems/issues/665

Update to Ruby-2.2.3

---

pkgs/ruby.yaml

Without this I can't build ruby on OSX, it fails with:
~~~~
[...]
compiling ./enc/encdb.c
linking encoding encdb.bundle
ld: warning: directory not found for option '-L/usr/local/lib'
Undefined symbols for architecture x86_64:
"_rb_enc_set_base", referenced from:
_Init_encdb in encdb.o
"_rb_enc_set_dummy", referenced from:
_Init_encdb in encdb.o
"_rb_encdb_alias", referenced from:
_Init_encdb in encdb.o
"_rb_encdb_declare", referenced from:
_Init_encdb in encdb.o
"_rb_encdb_dummy", referenced from:
_Init_encdb in encdb.o
"_rb_encdb_replicate", referenced from:
_Init_encdb in encdb.o
"_rb_encdb_set_unicode", referenced from:
_Init_encdb in encdb.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** …

Enable shared library support in Ruby to work around OSX build failure

---

pkgs/boost/boost.yaml
pkgs/dolfin/dolfin.py
pkgs/mshr.yaml
pkgs/vtk/vtk.yaml

In the latest version of OS X (10.11), setting `DYLD_LIBRARY_PATH` and `DYLD_FALLBACK_LIBRARY_PATH` does not work as in earlier versions of OS X. Using rpath is therefore important. This PR fixes this problem for the FEniCS stack (#593).

rpath fixes for os x

---

pkgs/fftw_all.yaml
pkgs/pyfftw.yaml

fftw_all.yaml is a slight modification of original fftw.yaml that builds both single, double and long double versions of the fftw library. All these precision libraries are required by pyfftw, which is a Python wrapper of fftw.
I have only tested this on my own Ubuntu 14.10.

Adding fftw_all.yaml and pyfftw.yaml. 

---

pkgs/openblas.yaml

@mbareford and @tridelat, I think this should fix the archer build on login nodes. closes #867

fix typo on openblas yaml causing unbounded parallel make

---

pkgs/tmux.yaml

Depends on ncurses and libevent
~~~~
$ ldd default/bin/tmux
linux-vdso.so.1 (0x00007ffe11b17000)
libutil.so.1 => /lib64/libutil.so.1 (0x00007fb162df3000)
libtinfo.so.5 => /home/vbraun/Code/HashDist/hashstack/default/bin/../../../ncurses/rrad4h2o6kbn/lib/libtinfo.so.5 (0x00007fb162bc9000)
libevent-2.0.so.5 => /home/vbraun/Code/HashDist/hashstack/default/bin/../../../libevent/e7tw4jpegglw/lib/libevent-2.0.so.5 (0x00007fb162981000)
libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fb162766000)
libc.so.6 => /lib64/libc.so.6 (0x00007fb1623a4000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb162187000)
/lib64/ld-linux-x86-64.so.2 (0x0000563e4d5bd000)
~~~~

Initial add of tmux

---

pkgs/texlive.yaml

This only installs the binaries. To get a usable TeX distribution, one has to
also install the supporting files that are maintained separately.

Add TeX Live distribution

---

pkgs/fabric.yaml

The problem is that the default install creates the following directory
structure in lib/python2.7/site-packages:
fabfile  fabric  Fabric-1.10.2-py2.7.egg-info  tests
The previous workaround created this structure:
Fabric-1.10.2-py2.7.egg  site.py  site.pyc
Which causes the 'fabric' module not to be found in Hashdist. The new
workaround creates the following structure:
fabfile  fabric  Fabric-1.10.2-py2.7.egg-info
Now everything works as expected.

Better workaround for Fabric

---

pkgs/python/python.yaml

Otherwise, "hit develop" builds with python3 cannot use pip since it
wants to put new files into `site-packages/__pycache__`
~~~~
$ ./default/bin/pip3 install ipython glob2 pyyaml ld jinja2
...
PermissionError: [Errno 13] Permission denied: '/home/.../site-packages/__pycache__/decorator.cpython-35.pyc'
~~~~

Do not link the site-packages/__pycache__ directory

---

base/cmake_package.py
pkgs/doxygen.yaml
pkgs/doxygen/doxygen.yaml
pkgs/doxygen/libiconv_plug.patch

Few fixes to get things working for El Capitan.

OS X fixes

---

pkgs/boto.yaml
pkgs/ecdsa.yaml
pkgs/iptools.yaml
pkgs/iso8601.yaml
pkgs/optcomplete.yaml
pkgs/paramiko.yaml
pkgs/python-scp.yaml
pkgs/starcluster.yaml
pkgs/workerpool.yaml

This adds the StarCluster package and all the dependencies that were not already available in HashStack. It also updates paramiko to latest version 1.16.0 (required by StarCluster) and adds ecdsa as dependency to paramiko.

Add starcluster

---

pkgs/flufl_lock.yaml

This PR also updates the package to version 2.4.1, which adds support for Python 3.

flufl_lock: copy missing __init__.py to correct location

---

pkgs/python/python-from-host.yaml
suse.yaml

python-from-host: use HOST_PYTHON to get Python install dir

---

pkgs/libevent.yaml

The sourceforge link changed. Also, libevent moved to github so use that.

Libevent url change

---

pkgs/python/python.yaml

This is necessary to build pygments as noted in #536

Configure python 3.5 without ensurepip as well

---

pkgs/fabric.yaml
pkgs/ipykernel.yaml
pkgs/ipython.yaml
pkgs/ipywidgets.yaml
pkgs/jupyter-client.yaml
pkgs/jupyter-console.yaml
pkgs/nbformat.yaml
pkgs/notebook.yaml
pkgs/qtconsole.yaml
pkgs/setuptools.yaml

This depends on #849. This PR only adds the patches from 25cfd55 up.
IPython requires setuptools > 18.5, so we need to update setuptools which triggers a rebuild of everything. But things seem to work.

Update Jupyter to the latest releases

---

pkgs/py.yaml

See #922 
py is a dependence of py.test and recent bump requires py to be >= 1.4.29

Bumping version of py as required by recent bump in py.test

---

pkgs/clang.yaml
pkgs/llvm.yaml

Both Julia and Numba also depend on 3.7, so this is a good change to do. We don't have a package for Numba yet, and Julia would need more work anyway, so in this PR I just update LLVM and Clang.

Upgrade LLVM to 3.7

---

pkgs/chrono.yaml

@cekees I got a similar error as https://github.com/hashdist/hashstack/issues/395 when trying to build chrono on CentOS.
Making bzip2 an explicit dependency for chrono fixed it.

chrono: added bzip2 as explicit dependency

---

pkgs/host-jpeg.yaml
pkgs/jpeg.yaml
pkgs/nasm.yaml

Libjpeg is a requirement for pillow starting with version 3
There are multiple implementations, but libjpeg-turbo seems to be popular.

Add libjpeg(-turbo)

---

pkgs/numpy/numpy.yaml

Somewhere between numpy version 1.8 and 1.11 the dependencies changed from distutils to cython
and setuptools.
So I am not sure how this type of dependency should be handled, because now the _extends_ section of  yaml configuration file has to be changed accordingly.

update numpy yaml to support version 1.11

---

pkgs/parmetis/clang_max_jbufs.patch
pkgs/parmetis/parmetis.yaml

clang 7.3 requires MAX_JBUFS < 25

patch MAX_JBUFS=24 in parmetis on OS X

---

pkgs/cython.yaml

The previous download url does not work any more, and cython.org had a major service interruption a month ago. Use the pypi download url instead.

Update to Cython 0.24.1

---

pkgs/node.yaml

GCC6 workaround, required on Fedora 24

Workaround for incorrect nodejs code

---

pkgs/cbcblock.yaml

This PR updates the recipe for cbc.block to point to its latest master

Point cbcblock to the latest master

---

pkgs/chrono.yaml
pkgs/geos.yaml
pkgs/irrlicht/irrlicht.yaml
pkgs/perl.yaml
pkgs/python-netcdf4.yaml
pkgs/readline.yaml

A couple of packages updates for compiling with gcc 6.2.1 (using arch linux).
When compiling with gcc 6, zoltan can to be commented out in `examples/proteus.linux2.yaml` as the current version throws an error

stable/proteus: updated yaml files of pkgs for gcc 6 compilation

---

pkgs/python/python.yaml

Without it, Python cannot handle regular expressions involving 4-byte
unicode chars. This is also the default in Python >= 3.3
I just tripped over this:
~~~~
In [1]: import re
In [2]: re.compile(u'[\U00010000-\U0010ffff]')
error: bad character range
~~~~
Whereas it works with the system python2 and python3 on Fedora, probably all other distros too.

Build Python 2.7 with UCS-4 enabled

---

pkgs/zmq.yaml

The old zeromq download url is apparently defunct. While we are at it,
update to the latest legacy stable release.

Change zeromq download url to github

---

pkgs/git.yaml

The old git 2.4.0 doesn't compile on osx sierra any more, fixed in the latest and greatest
~~~~
2017/03/05 23:49:32 - INFO: [package:run_job]     AR xdiff/lib.a
2017/03/05 23:49:32 - INFO: [package:run_job]     LINK git-credential-store
2017/03/05 23:49:32 - INFO: [package:run_job] ld: library not found for -lrt
2017/03/05 23:49:32 - INFO: [package:run_job] clang: error: linker command failed with exit code 1 (use -v to see invocation)
2017/03/05 23:49:32 - INFO: [package:run_job] make: *** [git-credential-store] Error 1
~~~~

Update to git-2.12.0
